# Site settings
title: 元峰GPT
SEOTitle: 元峰GPT
header-img: img/home-bg.jpg
email: metafeng09@gmail.com
description: "AI破局俱乐部， 玩赚GPT。AI的iPhone时刻来了，现在在AI领域学习一年，相当于在其他行业混10年。"
keyword: "博客, 个人网站, 互联网, Python, AI, ChatGPT, GPT, GPT4"
url: "https://metafeng.github.io"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'
                           # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: false
# weibo_username:    huifeng09
zhihu_username:     hufe09
github_username:    hufe09
twitter_username:   metafeng09
#facebook_username:  hufe09
#linkedin_username:  firstname-lastname-idxxxx



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 15
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN



# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]
# gem 'jekyll-paginate', group: :jekyll_plugins



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1



# Disqus settings
disqus_username: hufe09

# Netease settings
netease_comment: false



# Analytics settings
# Baidu Analytics
ba_track_id: f3833dc7372738e419314929e084eb18

# Google Analytics
ga_track_id: 'UA-140012449-1'            # Format: UA-xxxxxx-xx
ga_domain: hufe09.github.io



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "编程改变世界<br>The program changes the world."
sidebar-avatar: /img/avatar-hf.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: true



# Friends
# friends: [
#         title: "Hux Blog",
#         href: "http://huangxuan.me"
# ]
